### ISSUE TITLE
Problem With --mono_date Variable.

### ISSUE THREAD

**Issue by Hadir-05** [VSainteuf/utae-paps#22]
Hello Sir, how can I initialize the --mono_date variable, because when I run the code, an error appears with   " **if "-" in mono_date**
### **TypeError: argument of type 'NoneType' is not iterable**. Do you have any suggestions for solving this problem?
Thank you in advance.

**Comment by VSainteuf** [comment]
Hi @Hadir-05 , 
It looks like the same issue as [this one](in the dataset repo). I'll push the same fix.
Cheers

**Comment by Hadir-05** [comment]
> 

Hi @VSainteuf, 
Ok thank you very much, now I executed the code with the oldest version of dataset repo before your update, It looks that is working but I will wait the execution finish and look what happened. Anyway, Tahnk you for your response.

**Comment by VSainteuf** [comment]
Yes I actually already fixed it in November, so it should work after you pulled the latest version. 
Cheers

**Comment by Hadir-05** [comment]
> Yes I actually already fixed it in November, so it should work after you pulled the latest version. Cheers

But the problem is, the oldest version that is work for me, not the fixed in November, it's weird but I will wait until the end of the training.
Thank you Sir.

**Comment by VSainteuf** [comment]
Ah yes indeed, it was a fix for another problem. I'll correct it.

**Comment by VSainteuf** [comment]
Can you try with the latest version now ?

**Comment by Hadir-05** [comment]
> Can you try with the latest version now ?

Ok i run it now with latest version, i will tell you if there is any problem, Thank you.
