### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by clotilda-0** [VSainteuf/utae-paps#29]
from utils.dataset import ijgiDataset as Dataset 
SITSMamba-main/Main_SITSMamba.py 
Possible fix please @VSainteuf

**Comment by VSainteuf** [comment]
Hi @clotilda-0 I don't think your issue refers to the utae-paps repository as it does not contain an `ijgiDataset` nor a `Main_SITSMamba.py` script.
