### ISSUE TITLE
How to perform predictions for a single image. (parcels predicted)

### ISSUE THREAD

**Issue by alexanderDuenas** [VSainteuf/utae-paps#4]
Hi, 

There is any function/script in the code to perform predictions from the model using a single input image? I want to reproduce the qualitative results of the panoptic process (panoptic mask parcels predict) show in figure 12 in the paper. thanks

**Comment by VSainteuf** [comment]
Hi @alexanderDuenas,
We did not include the visualisation scripts in the repo yet but probably will. 
In the mean time here are some indications:  the paps module returns a dictionary of tensors containing the predictions at different levels of the module. The final panoptic predictions are contained in two tensors "pano_instance" and "pano_semantic". The first, gives the non-overlapping instance masks for a batch of inputs, and the second gives the predicted class for each pixel. Using those two tensors you should be able to visualize the predictions qualitatively.

**Comment by Auroralyxa** [comment]
Hello, I also want to predict a single image, do you know how to visualize it now?
Can you share the code?

**Comment by Auroralyxa** [comment]
Hello, I also want to predict a single image, do you know how to visualize it now?
Can you share the code?
thanks
