### ISSUE TITLE
A couple of questions about the data set

### ISSUE THREAD

**Issue by Lzqlzq123123** [VSainteuf/utae-paps#7]
Hi, I want to replace the original dataset with my own, but I don't know how some NPY files are generated (e.g. INSTANCE_Id file, it seems to add some boundaries and determine the background), could you explain

**Comment by VSainteuf** [comment]
Hi @Lzqlzq123123 ,
So at a high level you only need two arrays for each patch: 
- the semantic labels (providing the semantic class of each pixel),
- the instance labels (providing the unique instance id of each pixel).

The dataset class for utae-paps also loads two other arrays: 
- the centerness ground truth,
- the pixel to object mapping (or ZONES array see [this issue](https://github.com/VSainteuf/utae-paps/issues/6#issue-1084887438)). 
These two additional arrays are computed from the array of instance ids as shown in [one script](https://github.com/VSainteuf/pastis-benchmark/blob/b62a6f8d44d27bd9d77d302c4acc4903849bff72/code/centerness_ground_truth.py) of the dataset repo.

Once you have those 4 arrays for each patch, you can just modify the `__getitem__` of the [dataset class](https://github.com/VSainteuf/pastis-benchmark/blob/b62a6f8d44d27bd9d77d302c4acc4903849bff72/code/dataloader.py#L205-L239) to load them from your specific format and attribute them to `pixel_semantic_annotation`, `instance_ids`, `heatmap`, and `pixel_to_object_mapping`.
